### ISSUE TITLE
Configure support tools

### ISSUE THREAD

**Issue by Argmaster** [UniversityOfGdanskTeamPython/epseon_nn#2]
(Mostly) Python:
- pre-commit
- ruff
- poetry
- pytest
- pytest-cov
- codecov?
- prettier
- mkdocs

https://github.com/Argmaster/pygerber

**Comment by MatSzpy** [comment]
I’ve created documentation that includes (previously selected) support tools and a set of information about environment that everyone should use during project development. This should make work easier, faster and help team members focus on more important issues related to the functionality of the program itself. Before implementing the support tools listed in this documentation, they should be checked whether they all work properly.

**Comment by Argmaster** [comment]
+ Installation
+ Decelopment
+ Build from source
+ Build documentation

**Comment by MatSzpy** [comment]
I've checked and corrected the previous documentation. From now on, all support tools should work correctly in the environment of each team member. Additionally, I've updated the README.md file with key information about adding support tools to other team members' workspaces.
